### ISSUE TITLE
Add a Next and Previous options

### ISSUE THREAD

**Issue by kylekce** [asif-jalil/scroll-carousel#37]
It would have been nice if there were an option/method to allow an easy way to see the next or previous item while you're not scrolling by adding buttons, and maybe another feature that can swipe the carousel by clicking and dragging the mouse.

**Comment by asif-jalil** [comment]
Hello @kylekce ,
Thanks for this great feature idea. If the feature will be implemented, that will be great. However, the main concept of the scroll carousel will be distracted by implementing this feature because our purpose was to move this carousel on when scrolling. So I think this feature is not properly aligned with the main concept.
Thank you.
